### PR TITLE
Use lower minSdkVersion

### PR DESCRIPTION
**Pull request by AndyFrench**

### CODE REVIEW

**Comment by pedrovgs** [comment]
Hi @AndyFrench can you review the Travis-CI configuration for your branch? You've updated the ``buildToolsVersion`` from 23.0.1 to 23.0.2 but the Travis-CI configuration is the same. Maybe Travis-CI environments does not support that library.

I'd also like to know why have you changed the ``versionCode`` and ``versionName``.

**Comment by anothem** [comment]
You would need to update the build tools version in .travis.yml as well, but at the moment travis doesn't seem to know about 23.0.2 so even doing that wouldn't work. Have to stay on 23.0.1 until they update on Travis-side (saw a commit for it today, so probably will be fixed soon)

**Comment by AndyFrench** [comment]
Reverted the unnecessary changes now. Sorry about that

**Comment by pedrovgs** [comment]
@flipper83 can you review this PR?

**Comment by flipper83** [comment]
I've tested and we have a problem, before api 15 some permissions don't exist, we have a issue open with this problem (https://github.com/Karumi/Dexter/issues/3) and we can not put this pull request in master until the problem with permission that not exist have been solved. The best solution is not merge in master, merge it in other branch support-api-10 for example. Sounds good for you @pedrovgs ?

**Comment by pedrovgs** [comment]
Ok :+1:

**Comment by davideme** [comment]
But this is already the case with the actual min version right (API 14) ?
So, if it's a missing feature for API 14 why not lowering to API 10 anyway ?

**Comment by pedrovgs** [comment]
The previous min sdk was 14. This branch can go directly to master :) You have my :+1:

**Comment by flipper83** [comment]
ok, go ahead! but can we put a note on the readme, that before api 15 some permissions don't exist?

**Comment by pedrovgs** [comment]
Thanks for your @AndyFrench we will publish this change with the next release!!

**Pull request merged**
