### PR TITLE
Fix race condition

### PR DESCRIPTION
**Pull request by Serchinastico**
There is a race condition causing crashes in some situations.

The flow is the following:

1. Begin `continuePendingRequestIfPossible`
2. `pendingPermissions` is NOT empty
3. `rationaleAccepted` has NOT been accepted
4. --- Previous thread executes `onPermissionsChecked`
5. --- Clean pending permissions, rationaleAccepted and all internal state, including `this.activity`
6. Call `onActivityReady` with `this.activity`
7. `androidPermissionService.checkSelfPermission(activity, permission);` causes a NPE

Solution: Create a mutex separating execution of two critical snippets, the one cleaning the activity and the one using it to check for permissions.

### CODE REVIEW

**Comment by davideme** [comment]
:+1:

**Comment by flipper83** [comment]
:+1:

**Comment by pedrovgs** [comment]
:+1: Thanks for the fix @Serchinastico are we going to publish a new version?

**Comment by Serchinastico** [comment]
Yes, it will be 2.2.1

**Pull request merged**
