### PR TITLE
Add a workaround for RuntimeException when checking self permissions

### PR DESCRIPTION
**Pull request by rfgamaral**
Closes issue #86.

### CODE REVIEW

**Comment by Serchinastico** [comment]
Do you mind creating a test inside `DexterInstanceTest`?

**Comment by rfgamaral** [comment]
> Do you mind creating a test inside DexterInstanceTest?
To be honest - and I'm completely ashamed of this - I never did a single Android unit test.

But let me see if I can do it myself for the first time... :smiley:

**Comment by rfgamaral** [comment]
Sorry man, I tried but I couldn't get this to work... I've done lots of JavaScript unit tests but never done them on Android and I'm not familiarized with the testing frameworks and best practices.

For reference, here's my attempt:

```
@Test public void onPermissionDeniedByRuntimeExceptionParcelReadException() {
    givenPermissionIsCheckedWithRuntimeException(ANY_PERMISSION);

    whenCheckPermission(permissionListener, ANY_PERMISSION);
    whenContinueWithTheCheckPermissionProcess(permissionListener);

    thenPermissionIsDenied(ANY_PERMISSION);
}

private void givenPermissionIsCheckedWithRuntimeException(String permission) {
    when(androidPermissionService.checkSelfPermission(activity, permission)).thenThrow(
        new RuntimeException()).thenReturn(PackageManager.PERMISSION_DENIED);
}
```

Was I close?

**Comment by Serchinastico** [comment]
Haha, don't worry too much about it, I'll give it an attempt this afternoon and add it to Dexter afterwards. I have to say that your attempt looks promising but I'd have to analyze in more detail to see what's wrong.

**Pull request merged**
