### PR TITLE
Update build tools and google libraries

### PR DESCRIPTION
**Pull request by pedronveloso**
Bring these things up-to-date, specially the google libs since this way people don't get multiple versions into the final executable if they're using them as well.

### CODE REVIEW

**Comment by Serchinastico** [comment]
Latest version of the build tools is `23.0.3`. You should update the travis configuration to install that version in the worker as well. Keep in mind that it will force us to also include `tools` in the configuration as indicated in this issue https://github.com/travis-ci/travis-ci/issues/5036

Fix the travis build and :+1:

**Comment by pedronveloso** [comment]
@Serchinastico I've updated the Travis configuration which seemed pretty straight forward, but I'vent used Travis before so I guess I missed something. I'll read up on the Travis docs, thanks ;)

**Comment by pedronveloso** [comment]
Nailed it, I missed the sample was building on Travis as well the first time. Thanks for the tip :wink:

**Comment by pedrovgs** [comment]
:+1:

**Comment by pedrovgs** [comment]
Thanks for your contribution @pedronveloso :)

**Pull request merged**
